version: "3.8"
services:
  web-app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - web-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web-app
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge